# Generated by Django 4.2.1 on 2023-06-06 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smsuser', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Supermarket_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smsuser.supermarket'),
        ),
        migrations.AddField(
            model_name='order',
            name='Supermarketname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smsuser.supermarket'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='supermarket',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='smsuser.supermarket'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(through='customer.CartItem', to='customer.product'),
        ),
    ]
