# Generated by Django 4.2.1 on 2023-06-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Stock',
        ),
        migrations.AddField(
            model_name='product',
            name='onstock',
            field=models.BooleanField(default=True),
        ),
    ]
