# Generated by Django 4.2.1 on 2023-06-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_coupon_min_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='House',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
