# Generated by Django 4.2.1 on 2023-06-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_customer_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='District',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='Postalcode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='Province',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
