# Generated by Django 4.2.1 on 2023-06-13 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_customer_district_customer_postalcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Appartmentname',
        ),
    ]
