# Generated by Django 4.2.1 on 2023-06-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_order_delivery_option_order_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_slot',
            field=models.CharField(blank=True, choices=[('10 AM to 12 PM', '10:00 AM - 12:00 PM'), ('12 PM to 2 PM', '12:00 PM - 2:00 PM'), ('2 PM to 4 PM', '2:00 PM - 4:00 PM'), ('4 PM to 6 PM', '4:00 PM - 6:00 PM'), ('6 PM to 8 PM', '6:00 PM - 8:00 PM'), ('8 PM to 10 PM', '8:00 PM - 10:00 PM'), ('10 PM to 12 AM', '10:00 PM - 12:00 AM')], max_length=50, null=True),
        ),
    ]
