# Generated by Django 4.2.1 on 2023-06-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_alter_order_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentmethod',
            field=models.CharField(default='COD', max_length=4),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_slot',
            field=models.CharField(blank=True, choices=[('10 AM-12 PM', '10:00 AM - 12:00 PM'), ('12 PM-2 PM', '12:00 PM - 2:00 PM'), ('2 PM-4 PM', '2:00 PM - 4:00 PM'), ('4 PM-6 PM', '4:00 PM - 6:00 PM'), ('6 PM-8 PM', '6:00 PM - 8:00 PM'), ('8 PM-10 PM', '8:00 PM - 10:00 PM'), ('10 PM-12 AM', '10:00 PM - 12:00 AM')], max_length=50, null=True),
        ),
    ]
