# Generated by Django 4.2.1 on 2023-06-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_order_couponcodeapplied_order_discount_orderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='final_total',
            field=models.DecimalField(decimal_places=2, default=250, max_digits=8),
        ),
    ]
