# Generated by Django 4.2.1 on 2023-06-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_product_discount_product_final_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='final_total',
            field=models.IntegerField(),
        ),
    ]
