# Generated by Django 4.2.1 on 2023-06-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_alter_product_price_alter_product_final_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Discount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='final_total',
            field=models.FloatField(),
        ),
    ]
