# Generated by Django 4.2.1 on 2023-07-01 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smsuser', '0004_alter_supermarket_slug'),
        ('customer', '0022_alter_product_discount_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='Supermarket_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smsuser.supermarket'),
        ),
        migrations.AlterField(
            model_name='order',
            name='OrderId',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_ID',
            field=models.CharField(max_length=20, unique=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
