# Generated by Django 4.2.1 on 2023-07-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_categories_supermarket_name_alter_order_orderid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_ID',
            field=models.CharField(max_length=20),
        ),
    ]
