# Generated by Django 4.2.1 on 2023-07-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_ID',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.CharField(max_length=50),
        ),
    ]
