# Generated by Django 4.2.1 on 2023-07-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_alter_categories_category_id_alter_categories_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='City',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='District',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='House',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Landmark',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Mobile',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Postalcode',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Province',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Street',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
