# Generated by Django 4.2.1 on 2023-06-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsuser', '0002_user_is_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='supermarket',
            name='slug',
            field=models.CharField(default='super1', max_length=20),
        ),
    ]
