# Generated by Django 4.2.1 on 2023-06-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsuser', '0003_supermarket_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supermarket',
            name='slug',
            field=models.CharField(max_length=20),
        ),
    ]
