# Generated by Django 4.2.1 on 2023-07-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsuser', '0004_alter_supermarket_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='customer/')),
                ('title', models.CharField(max_length=100, null=True)),
                ('offerbrand', models.CharField(max_length=20, null=True)),
                ('offerdetails', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
